ALTER TABLE waitlist ADD COLUMN utm_source TEXT DEFAULT NULL;
ALTER TABLE waitlist ADD COLUMN utm_medium TEXT DEFAULT NULL;
ALTER TABLE waitlist ADD COLUMN utm_campaign TEXT DEFAULT NULL;
ALTER TABLE waitlist ADD COLUMN utm_content TEXT DEFAULT NULL;
